backend:
    name: git-gateway
    branch: master

media_folder: "static/uploads"
public_folder: "uploads"

collections:
    - name: "blog"
      label: "Blog"
      folder: "content/blog"
      create: true
      slug: "{{year}}-{{slug}}"
      fields:
        - { label: "Title", name: "title" , widget: "string" , required: true}